export const CATS_CALL = 'CATS_CALL';
export const CATS_CALL_SUCCESS = 'CATS_CALL_SUCCESS';
export const CATS_CALL_FAILED = 'CATS_CALL_FAILED';

export const CATS_CALL_MORE = 'CATS_CALL_MORE';
export const CATS_CALL_MORE_SUCCESS = 'CATS_CALL_MORE_SUCCESS';
export const CATS_CALL_MORE_FAILED = 'CATS_CALL_MORE_FAILED';