export const CATEGORIES_CALL = 'CATEGORIES_CALL';
export const CATEGORIES_CALL_SUCCESS = 'CATEGORIES_CALL_SUCCESS';
export const CATEGORIES_CALL_FAILED = 'CATEGORIES_CALL_FAILED';
export const SET_CURRENT_CATEGORIES = 'SET_CURRENT_CATEGORIES';